const groups=[
['COMPROMETIMENTO',[
['Me conta uma vez em que você teve que entregar algo com prazo apertado. O que fez para dar conta?','Em projetos pessoais e trabalhos digitais, já precisei finalizar materiais em pouco tempo. Nessas situações, separo o que é essencial, organizo as etapas por prioridade e evito distrações até concluir. Prefiro entregar algo bem revisado dentro do prazo do que deixar tudo para o último momento.'],
['Quando chegam cinco coisas urgentes ao mesmo tempo, como decide o que fazer primeiro?','Primeiro identifico o que tem prazo mais curto e o que pode gerar maior impacto se atrasar. Depois organizo as demais tarefas em uma sequência clara. Se houver conflito de prioridades, confirmo com o responsável em vez de simplesmente escolher por conta própria.'],
['O que te fez querer trabalhar aqui, e não em outro escritório?','A oportunidade me chamou atenção por unir ambiente administrativo, contato com tecnologia e possibilidade de aprendizado. Também valorizo a ideia de entrar em um lugar onde eu possa evoluir, assumir responsabilidades e construir uma trajetória, não apenas ocupar uma vaga.']]],
['LEALDADE E SIGILO',[
['Já viu algo errado ou uma informação delicada no trabalho? O que fez com isso?','Entendo que informações internas devem permanecer com quem realmente precisa delas. Se eu identificasse algo inadequado ou delicado, evitaria comentários com terceiros e levaria a situação de forma reservada à pessoa responsável.'],
['Um cliente pede um dado de outro cliente “porque são amigos”. Como você responde?','Explicaria com educação que não posso fornecer informações de outro cliente sem autorização. Ser amigo não muda a responsabilidade da empresa com privacidade e sigilo.'],
['Um colega fala mal do escritório para você. O que você faz?','Eu evitaria alimentar a conversa. Se houver um problema real, acredito que o melhor caminho é tratar diretamente com quem pode resolver, e não transformar a situação em comentários entre colegas.']]],
['TRABALHO EM EQUIPE',[
['Descreva um conflito com um colega e como resolveu.','Em trabalhos e projetos em grupo, já tive divergências sobre a forma de executar uma tarefa. Procurei ouvir o motivo da outra pessoa, explicar meu ponto sem transformar a discordância em algo pessoal e chegar a uma solução que atendesse ao objetivo do grupo.'],
['Você prefere resolver tudo sozinho ou pedir ajuda cedo? Dá um exemplo.','Tento resolver primeiro aquilo que está ao meu alcance, mas não tenho problema em pedir ajuda quando percebo que insistir sozinho só vai atrasar o trabalho. Em tecnologia faço bastante isso: pesquiso, testo e, quando necessário, procuro alguém com mais experiência.'],
['Como você reage quando alguém corrige um erro seu na frente dos outros?','Procuro separar a forma da correção do conteúdo dela. Se eu errei, corrijo e aprendo. Depois, se a maneira como aconteceu me incomodar, converso em particular com a pessoa, sem criar conflito na frente dos demais.']]],
['POSTURA PROFISSIONAL',[
['Cliente irritado te cobra no WhatsApp por algo que não é da sua área. O que você escreve?','Eu responderia com educação, mostraria que entendi a solicitação e evitaria prometer algo que não depende de mim. Informaria que vou encaminhar a questão ao setor ou responsável correto e procuraria garantir que o cliente não fique sem retorno.'],
['Daqui a 5 anos, onde você se vê na vida?','Quero estar profissionalmente mais preparado, com experiência real, novas competências e mais responsabilidades. Minha intenção é olhar para trás e perceber uma evolução consistente, tanto profissional quanto pessoal.'],
['Se pudesse mudar uma coisa no seu último emprego, o que seria?','Como estou construindo minha experiência profissional, prefiro transformar essa pergunta no que busco desde o início: comunicação clara, espaço para aprender, responsabilidade e oportunidade de crescer conforme demonstro resultado.']]],
['SOBRE VOCÊ',[
['Você tem disponibilidade para fazer hora extra quando for necessário?','Sim. Quando houver necessidade real e alinhamento com a empresa, tenho disponibilidade para colaborar.'],
['Como é o seu conhecimento com inteligência artificial? Já usa no dia a dia?','Tenho bastante familiaridade com inteligência artificial e já a utilizo no dia a dia para pesquisa, organização, revisão de textos, desenvolvimento, criação visual e apoio na solução de problemas. Procuro usar IA como ferramenta, sempre conferindo e ajustando o resultado.'],
['Você acha que tem boa dicção, boa escrita e boa digitação no computador?','Considero minha escrita e digitação boas e tenho facilidade com computador. Na comunicação verbal, procuro falar com clareza e continuo buscando melhorar conforme ganho experiência em ambientes profissionais.'],
['Você se considera bom em desenrolar um conflito? Ou sente que tem dificuldade?','Considero que consigo lidar bem com conflitos quando mantenho a calma e entendo os dois lados. Não tento vencer uma discussão; procuro encontrar o problema real e uma solução prática.'],
['Você se acha esforçado? Por quê?','Sim. Quando quero aprender ou concluir algo, tenho persistência para pesquisar, testar, corrigir erros e continuar até conseguir um resultado satisfatório.']]],
['RAÍZES',[
['Você pretende que a nossa casa seja a sua casa também?','Sim. Se eu fizer parte da equipe, quero tratar o ambiente, os clientes, as informações e os resultados da empresa com responsabilidade, como algo do qual também faço parte.'],
['Você pretende criar raízes aqui, ou este trabalho seria apenas algo temporário?','Minha intenção é construir experiência e crescer junto com a empresa. Não estou procurando apenas algo para preencher um período; quero uma oportunidade em que dedicação e aprendizado possam virar uma trajetória.']]],
['PERGUNTAS ESPECÍFICAS',[
['Quais ferramentas de IA e automação você já usa no dia a dia? Dê exemplos práticos do que já fez com elas.','Uso ferramentas de IA como ChatGPT e outras soluções digitais para pesquisar, estruturar textos, estudar problemas, auxiliar em programação e desenvolver materiais visuais. Também tenho contato com scripts e automações, o que me ajuda a enxergar tarefas repetitivas como processos que podem ser simplificados.'],
['Pense em uma rotina repetitiva de um escritório. Como você automatizaria isso?','No exemplo dos boletos, manteria os dados organizados em uma planilha ou sistema, identificaria automaticamente quem precisa receber o lembrete, geraria mensagens personalizadas e faria o envio por uma integração autorizada. Também registraria data, status e possíveis falhas para permitir conferência humana e evitar envios duplicados ou incorretos.'],
['Você já ensinou alguém a usar uma ferramenta digital? Como foi? Tem paciência para isso?','Sim. Já ajudei pessoas com ferramentas, configurações e tarefas no computador. Costumo explicar por etapas e adaptar a explicação ao nível da pessoa. Tenho paciência, principalmente porque sei que algo simples para quem já conhece pode ser totalmente novo para outra pessoa.'],
['Trabalhar de forma flutuante entre setores, sem uma rotina fixa, te agrada ou te incomoda? Por quê?','Me agrada. Gosto da possibilidade de aprender funções diferentes e entender como as áreas se conectam. Desde que as prioridades estejam claras, consigo me adaptar bem e vejo essa variedade como uma oportunidade de aprender mais.']]]];
let n=1;const root=document.querySelector('#qa');groups.forEach(([title,items])=>{const s=document.createElement('section');s.className='group reveal';s.innerHTML=`<div class="group-title">${title}</div>`;items.forEach(([q,a])=>{s.innerHTML+=`<article class="card"><div class="num">${String(n++).padStart(2,'0')}</div><div><p class="q">${q}</p><p class="a">${a}</p></div></article>`});root.appendChild(s)});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
